#!/usr/bin/env python3
"""
Convert PNG icons to LVGL C-array image files.
Outputs RGB565 format matching LV_COLOR_DEPTH 16.

Usage:
  pip install Pillow
  python convert_icons.py

Generates .c files in ../src/icons/ ready to #include.
"""
import os
import struct
from PIL import Image

ICONS = {
    "flame_32":    {"file": "flame_32.png",    "size": 32},
    "seedling_32": {"file": "seedling_32.png", "size": 32},
    "refresh_32":  {"file": "refresh_32.png",  "size": 32},
    "moon_32":     {"file": "moon_32.png",     "size": 32},
    "sun_32":      {"file": "sun_32.png",      "size": 32},
}

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "icons")


def rgb888_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def convert_icon(name, info):
    img = Image.open(os.path.join(os.path.dirname(__file__), info["file"]))
    size = info["size"]
    img = img.resize((size, size), Image.LANCZOS)
    img = img.convert("RGBA")

    has_alpha = any(px[3] < 255 for px in img.getdata())
    cf = "LV_IMG_CF_TRUE_COLOR_ALPHA" if has_alpha else "LV_IMG_CF_TRUE_COLOR"

    pixels = list(img.getdata())
    data_bytes = []

    for px in pixels:
        r, g, b, a = px
        c565 = rgb888_to_rgb565(r, g, b)
        # Little-endian 16-bit + alpha byte
        data_bytes.append(c565 & 0xFF)
        data_bytes.append((c565 >> 8) & 0xFF)
        if has_alpha:
            data_bytes.append(a)

    # Write C file
    os.makedirs(OUT_DIR, exist_ok=True)
    c_path = os.path.join(OUT_DIR, f"icon_{name}.c")
    h_path = os.path.join(OUT_DIR, f"icon_{name}.h")

    with open(c_path, "w") as f:
        f.write(f"// Auto-generated by convert_icons.py\n")
        f.write(f'#include "icon_{name}.h"\n\n')
        f.write(f"static const uint8_t icon_{name}_data[] = {{\n")
        for i, b in enumerate(data_bytes):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{b:02X}, ")
            if i % 16 == 15:
                f.write("\n")
        f.write("\n};\n\n")
        f.write(f"const lv_img_dsc_t icon_{name} = {{\n")
        f.write(f"    .header.always_zero = 0,\n")
        f.write(f"    .header.w = {size},\n")
        f.write(f"    .header.h = {size},\n")
        bpp = 3 if has_alpha else 2
        f.write(f"    .data_size = {size * size * bpp},\n")
        f.write(f"    .header.cf = {cf},\n")
        f.write(f"    .data = icon_{name}_data,\n")
        f.write(f"}};\n")

    with open(h_path, "w") as f:
        guard = f"ICON_{name.upper()}_H"
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(f"#include <lvgl.h>\n\n")
        f.write(f"extern const lv_img_dsc_t icon_{name};\n\n")
        f.write(f"#endif // {guard}\n")

    print(f"  ✓ {name}: {size}x{size}, {cf}, {len(data_bytes)} bytes -> {c_path}")


if __name__ == "__main__":
    print("Converting icons to LVGL C arrays...")
    for name, info in ICONS.items():
        convert_icon(name, info)
    print(f"\nDone! Files in {OUT_DIR}")
    print("Add the .c files to your platformio build and #include the .h files.")
